'use client';

import React, { useEffect, useState } from 'react';
import { Download, Mailbox, RefreshCw, Sparkles, Volume2, VolumeX, WifiOff } from 'lucide-react';
import { Panel, PanelBody, PanelHeader } from '@/components/ui/Panel';
import { Button } from '@/components/ui/Button';
import { Segmented } from '@/components/ui/Field';
import { useApp } from '@/contexts/AppContext';
import { writeFutureLetter } from '@/lib/ai';
import { useSpeechSynthesis } from '@/hooks/useSpeech';
import { read, write } from '@/lib/storage';
import { cn, formatCurrency, formatDate, getTodayDate } from '@/lib/utils';

type Horizon = '5' | '10' | '20';

interface StoredLetter {
  years: number;
  text: string;
  live: boolean;
  writtenAt: string;
}

const LETTERS_KEY = 'smartwise_letters';

/**
 * A letter from the user's future self, extrapolated from their real data.
 *
 * The tone is not random — it is decided by their actual savings rate. Someone
 * saving nothing gets a letter about what it cost; someone saving well gets one
 * about what compounded.
 */
export const FutureSelfLetter: React.FC = () => {
  const { aiContext, player, budget, streak, smartwiseScore, awardXP } = useApp();
  const [horizon, setHorizon] = useState<Horizon>('10');
  const [letters, setLetters] = useState<Record<string, StoredLetter>>({});
  const [loading, setLoading] = useState(false);
  const [rewarded, setRewarded] = useState(false);

  const { speak, stop, speaking, supported: ttsSupported } = useSpeechSynthesis();

  useEffect(() => {
    setLetters(read<Record<string, StoredLetter>>(LETTERS_KEY, {}));
  }, []);

  const letter = letters[horizon];

  const savingsRate =
    player.monthly_allowance > 0
      ? (player.monthly_allowance - budget.spentThisMonth) / player.monthly_allowance
      : 0;

  const generate = async () => {
    setLoading(true);
    stop();
    const result = await writeFutureLetter(aiContext, Number(horizon));
    const stored: StoredLetter = {
      years: Number(horizon),
      text: result.text,
      live: result.live,
      writtenAt: getTodayDate(),
    };
    const next = { ...letters, [horizon]: stored };
    setLetters(next);
    write(LETTERS_KEY, next);
    setLoading(false);

    if (!rewarded) {
      setRewarded(true);
      awardXP(100, 'Read a letter from your future self');
    }
  };

  const download = () => {
    if (!letter) return;
    const blob = new Blob(
      [
        `A letter from ${player.name || 'you'}, ${letter.years} years from now\n`,
        `Written ${formatDate(letter.writtenAt)} · Smartwise Score ${smartwiseScore.score}/100\n`,
        '─'.repeat(60),
        '\n\n',
        letter.text,
        '\n\n',
        '─'.repeat(60),
        '\nGenerated by Smartwise from your real spending data.\n',
      ],
      { type: 'text/plain;charset=utf-8' }
    );
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `letter-from-${letter.years}-years-ahead.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const toneHint =
    savingsRate < 0.1
      ? { label: 'This one will sting', className: 'chip-negative' }
      : savingsRate < 0.2
        ? { label: 'Cautiously hopeful', className: 'chip-warning' }
        : { label: 'This one is proud', className: 'chip-positive' };

  return (
    <Panel>
      <PanelHeader
        title="Letter from your future self"
        subtitle="Written from your real numbers, not a template"
        icon={<Mailbox className="h-3.5 w-3.5" />}
        action={
          <Segmented
            options={[
              { value: '5', label: '5 yrs' },
              { value: '10', label: '10 yrs' },
              { value: '20', label: '20 yrs' },
            ]}
            value={horizon}
            onChange={setHorizon}
          />
        }
      />

      <PanelBody className="space-y-4">
        {/* What the letter is built from */}
        <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4">
          {[
            {
              label: 'Savings rate',
              value: `${Math.round(savingsRate * 100)}%`,
              tone: savingsRate < 0.1 ? 'text-negative' : savingsRate < 0.2 ? 'text-warning' : 'text-positive',
            },
            { label: 'Monthly saving', value: formatCurrency(Math.max(0, budget.remaining), true), tone: 'text-ink' },
            { label: 'Smartwise Score', value: String(smartwiseScore.score), tone: 'text-ink' },
            { label: 'Streak', value: `${streak.current}d`, tone: 'text-ink' },
          ].map((stat) => (
            <div key={stat.label} className="rounded-lg border border-line bg-surface p-2.5">
              <p className="eyebrow">{stat.label}</p>
              <p className={cn('text-sm font-semibold tabnum', stat.tone)}>{stat.value}</p>
            </div>
          ))}
        </div>

        {!letter ? (
          <div className="space-y-3 rounded-lg border border-dashed border-line-strong px-4 py-8 text-center">
            <Mailbox className="mx-auto h-7 w-7 text-faint" />
            <div className="space-y-1">
              <p className="text-sm font-medium text-ink">
                Nothing in the mailbox yet
              </p>
              <p className="mx-auto max-w-md text-xs leading-relaxed text-muted">
                Smartwise will write you a letter from {horizon} years ahead, extrapolated from your
                actual savings rate, your biggest spending category, and the goals you set. It is
                either going to be proud of you or disappointed — that part is up to your data.
              </p>
            </div>
            <span className={cn('chip', toneHint.className)}>
              Based on your numbers: {toneHint.label}
            </span>
            <div>
              <Button
                variant="primary"
                onClick={generate}
                loading={loading}
                icon={<Sparkles className="h-3.5 w-3.5" />}
              >
                Open the letter
              </Button>
            </div>
          </div>
        ) : (
          <article className="space-y-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="flex items-center gap-1.5">
                <span className={letter.live ? 'chip chip-accent' : 'chip'}>
                  {letter.live ? (
                    <>
                      <Sparkles className="h-2.5 w-2.5" /> Gemini
                    </>
                  ) : (
                    <>
                      <WifiOff className="h-2.5 w-2.5" /> Offline
                    </>
                  )}
                </span>
                <span className="chip">Written {formatDate(letter.writtenAt)}</span>
              </div>
              <div className="flex items-center gap-1">
                {ttsSupported && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => (speaking ? stop() : speak(letter.text))}
                    icon={
                      speaking ? <VolumeX className="h-3 w-3" /> : <Volume2 className="h-3 w-3" />
                    }
                  >
                    {speaking ? 'Stop' : 'Read aloud'}
                  </Button>
                )}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={download}
                  icon={<Download className="h-3 w-3" />}
                >
                  Save
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={generate}
                  loading={loading}
                  icon={<RefreshCw className="h-3 w-3" />}
                >
                  Rewrite
                </Button>
              </div>
            </div>

            <div className="relative overflow-hidden rounded-xl border border-line bg-surface">
              <div className="pointer-events-none absolute inset-0 grid-noise opacity-30" />
              <div className="relative px-5 py-6 sm:px-8 sm:py-8">
                <p className="eyebrow mb-4">
                  {new Date().getFullYear() + letter.years} · from {player.name || 'you'}
                </p>
                <div className="whitespace-pre-line text-sm leading-[1.85] text-ink">
                  {letter.text}
                </div>
              </div>
            </div>

            <p className="text-[10px] leading-relaxed text-faint">
              This letter is a projection generated from the data you have logged, using a 12%
              annual return assumption. It is a motivational tool, not a forecast.
            </p>
          </article>
        )}
      </PanelBody>
    </Panel>
  );
};
